version: '3'

services:
  hwmanager-server:
    build:
      context: flask
    image: hwmanager-server
    container_name: 'hwmanager-server'
    volumes:
      - ./nginx/:/etc/nginx/
      - ./data/:/usr/src/app/data/
    ports:
      - 3000:3000
  hwmanager-client:
    image: nginx
    container_name: 'hwmanager-client'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html/:/etc/nginx/html
    ports:
      - 80:80